name: learn-bun
on: 
  push:
    branches:
      - main
jobs:
  server-test:
    run-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v3
        with:
          bun-version: latest
      - run: bun -v
      - run: bun run index.ts
